- .gitattributes
> Add .gitattributes to highlight .sw syntax as rust

- src/ecr.sw
Formerly, only `ec_recover_address` was implemented.
This fixes that by adding an `ec_recover` function.
Tests can be found in the Sway repo here: https://github.com/FuelLabs/sway/pull/626
> Adding the missing `ec_recover`functionality

- src/token.sw
- Adds a single function to allow the unconditional transfer of coins to a contract.
The tests can be found here: https://github.com/FuelLabs/sway/pull/697
> Adding the force_transfer function to the token lib.

- Forc.toml
- src/address.sw
Implements the `Eq` trait for `Address`using a wrapper around the `meq` opcode.
Test for this added here: https://github.com/FuelLabs/sway/pull/672
Blocked by https://github.com/FuelLabs/sway-lib-core/issues/8
> Implement the Eq trait for Address

- src/lib.sw
- src/option.sw
This is basically cloned from Result and adapted to fit the `Option` use case.
Tests to follow here: WIP: Tests are implemented but failing due to:
```
Option::Some(T) => {
|             ^^^^^^^^^^^^^^^ Unimplemented feature: ASM generation has not yet been implemented for this.
```
Adding the tests is  blocked by https://github.com/FuelLabs/sway/issues/579
Closes #24
> Add Option type & is_some/is_none methods

- src/b512.sw
- src/ecr.sw
Instead of 2 b256 fields in a struct we can use a 2 element array instead.
I found that both the assumptions about memory layout and all the copying was producing brittle code, and simplifying the ASM blocks as much as possible is a good thing.
> Simplify the B512 (and therefore ECR) code.

- src/token.sw
The 4th and final(for now) function for the token library.
>/// Transfer `amount` coins of type `asset_id` to address `recipient`.
The comments in the new function should provide a fairly clear explanation of what is going on.
Tests here: https://github.com/FuelLabs/sway/pull/722
> Adding the transfer_to_output function to token library

- src/chain/auth.sw
The Auth module makes use of the `gm` opcode in 2 places.
we currently do this:
```
asm(r1, r2: IS_CALLER_EXTERNAL) {
gm r1 r2;
r1: bool
}
```
Until now we haven't been able to properly test this, but today I found that what we have currently is wrong. The error is:
```
gm r1 r2;
^^^^^^^^^ This op expects 1 register(s) as arguments, but you provided 2 register(s).
```
This PR fixes that.
> bugfix: remove second register from gm opcode

- src/option.sw
- src/result.sw
`T` is a type name, so use `t` instead. Technically, `_` should be used, but that doesn't work yet, so at least this change should avoid errors popping up once inner values can be extracted from enums.
> Use `t` instead of `T` for `Result` matches.

- Forc.toml
- tests/Forc.toml
- tests/test_artifacts/balance_contract/Forc.toml
- tests/test_projects/token_ops/Forc.toml
Updating 'Forc.toml' files to use 'authors' instead of 'author'. This enables compatibility with the change being made in this PR https://github.com/FuelLabs/sway/pull/822
> change author to authors in Forc.toml files

- src/token.sw
Gets rid of this warning:
```
64 |         if type == OUTPUT_VARIABLE_TYPE {
|                    -------------------- This cast, from integer type of width sixty four to integer type of width eight, will lose precision.
```
Long term, I don't expect implicit casts to be a thing. We've started making some changes towards that and we will also need https://github.com/FuelLabs/sway/issues/878 at some point.
Also, one minor variable naming issue.
> Avoid implicit cast warning

- Forc.toml
Explicitly use `master` for the branch.
> Make core branch explicit

- src/registers.sw
A tiny change to reflect the fact that there are no wrapper functions to access the `zero` or `one` registers in this module.
> Correct inline docs for registers.sw

- tests/Forc.toml
- tests/test_artifacts/balance_contract/Forc.toml
- tests/test_projects/registers/Forc.toml
- tests/test_projects/token_ops/Forc.toml
The `path`s of dependencies should point to the directory containing
the dependency's `Forc.toml` (not the `src`). This commit fixes the
`Forc.toml`s of the test projects to account for this.
There was also a spuriuos Forc.toml at `tests/Forc.toml` which has been
removed.
_https://github.com/FuelLabs/sway/issues/923 related_
> Fix some `path`s in the test project dependencies

- src/contract_id.sw
The param is currently named `addr`, as the trait was copy-pasted from the Address::into trait.
this renames it to `id`.
> Rename param in the ContractId::into() implementation

- Forc.toml
- tests/test_artifacts/balance_contract/Forc.toml
- tests/test_projects/registers/Forc.toml
- tests/test_projects/token_ops/Forc.toml
This helps to resolve some dependency double-ups pending a proper solution in `forc`.
See https://github.com/FuelLabs/sway/issues/931 and https://github.com/FuelLabs/fuels-rs/pull/150#discussion_r825312119
> Prefer `https` over `http` for forc git dependency URLs

- Forc.toml
This will remove the need for specifying a `package` field for declarations of `std` under `[dependencies]` once https://github.com/FuelLabs/sway/issues/977 is implemented.
> Change `[project]` name from `lib-std` to `std`

- tests/test_projects/contract_id_type/mod.rs
- tests/test_projects/registers/mod.rs
- tests/test_projects/token_ops/mod.rs
This just:
- deals with compiler warnings
- applies `cargo fmt`
This will simplify review of another PR of mine with some of these changes in it as well.
> Cleanup stdlib tests

- tests/Cargo.toml
Default features were enabled for fuel-core causing rocksdb to be enabled and compiled. This was causing ulimit issues for some developers when running tests concurrently. This should also speed up build times a lot.
> Disable default features from fuel-core

- src/chain.sw
- src/lib.sw
- src/panic.sw
- src/result.sw
- src/token.sw
- tests/test_projects/option/src/main.sw
- tests/test_projects/result/src/main.sw
Implement `Result.unwrap()`.
I refactored `panic` into its own library, since otherwise `chain::auth` depends on `result`, which depends on `chain::panic`, which would be a circular dependency.
> Add `Result.unwrap()`
